### PR TITLE
Catalina fixes and Refactoring

### PR DESCRIPTION
**Pull request by dnnsmnstrr**
Here is the pull request I was talking about. 

Now you can accept (or reject) the changes I made. You should be able to see what was changed, so you can decide if the changes are useful.

What I did was add the refactored preset fix I already shared, in addition to some AppleScripts to show you how you can make their code visible in diffs. 
All you have to do is use the `.applescript` extension instead of `.scpt`, which is the compiled version. This would allow us to collaboratively work on scripts, being able to improve them over time with version control.
A next step could be figuring out how to run the scripts directly from the file instead of pasting the code into BTT. That might make things even more flexible in some cases.
I also created a .gitignore, which will stop git from adding the DS_Store files that are automatically created on MacOS

### CODE REVIEW

**Review by yuuiko — APPROVED** [review]

**Review by yuuiko — DISMISSED** [review]

**Comment by yuuiko** [comment]
Trying to figure out how this works, Thanks for the help.

Am I able to rename the AQT build you added or somehow track it back to your (user)name before merge? Also move it to a new folder (3.5.4 beta) before merge too.

Not sure if this was what you meant by "figuring out how to run the scripts directly from the file" but you can run and create applescripts in the "Script Editor" built-in app.

Thanks again for helping me through the git system!

**Comment by yuuiko** [comment]
uh let's click the big green button and see what happens

**Comment by dnnsmnstrr** [comment]
Great, now you should have my changes in your master branch.
So I found you can check out the pull request and make changes before merging (was able to do it directly in Atom).

I'm also just learning how this process works on GitHub. Guess you can always just roll back the changes if something goes wrong, so there's not really anything to lose when trying out the different Features. :smiley:

Regarding AppleScript, at some point I switched to using Atom with [this package](https://atom.io/packages/script) to test scripts directly from the editor (in cases where it made sense). 
What I mean by running scripts from the file is that I was thinking of trying to create actions in BTT that take a filepath to the local directory of your repository and run those scripts. Then you should be able to change a script, save it and immediately be able to use it with the action that is linked to it. Currently, when I update my scripts, I have to copy/paste to keep the version control in sync.

**Comment by yuuiko** [comment]
Yeah, BTT files don't work too well with git
We'd probably need to have a master to manually merge all the stuff from our copies into, but then its also hard to keep track of what we added and could cause conflict if we edit it at the same time and push...

Live / parallel collab probably won't work in this case, if collab is to go on we probably need to take turns editing the one file unless theres another solution (merging into a master from personal copies sounds very tedious and wiring could get all tangled.)

----

On another note...
I'm using on your copy as my main now and I used the youtube web widget only to see that the quickplay button disappeared (again)

Seems like Quickplay button in web widgets is inconsistent with the quickplay button in the strip.
I see you've replaced those with "Music" instead of "iTunes", so it's not appearing on my older OS.
This differs from my code of the one in the quickstrip, which doesn't reference any apps anymore:
````
--Thanks to @springles for his contribution to AQT!
--Posted: https://community.folivora.ai/t/1704/93?u=yyuuiko

try
	--@yuuiko: Get User Preference
	tell application "BetterTouchTool"
		try
			set UsrPref_CS_Highlighting to get_string_variable "CS_Highlighting"
		end try
	end tell
	
	if UsrPref_CS_Highlighting is "ON" then --@yuuiko: only activate if preferred by user.
		tell application "BetterTouchTool"
			try
				set showMediaControls to get_string_variable "BTTCurrentlyPlayingApp"
				set playerState to get_number_variable "BTTCurrentlyPlaying"
			on error
				return 0 -- Don't disappear on error
			end try
		end tell
		if showMediaControls is not missing value then
			if playerState is 1.0 then
				return 1 --Highlight
			else
				return 0 --Grey
			end if
		else
			return 0
		end if
	else
		return 0 --Grey
	end if
on error
	return 0 --if all else fails
end try
````

**Comment by dnnsmnstrr** [comment]
I might have mixed something up or forgotten some parts - didn't really do much testing. Mainly wanted to initiate some refactoring in AquaTouch, since I have some actions that are supposed to cycle through the widget groups and the inconsistent naming was making things confusing while developing them.

Just some ideas on collaboration: 
I definitely see the problems, which is why I've started building my presets to run in parallel with AquaTouch. Maybe instead of merging everything together you could also split some things into appropriate groups (Such as gestures or support for specific types of apps like development, design/productivity, etc.) 
There might be people that don't need all the supported apps and this would also increase import-performance in BTT. 
Maybe think of presets more like 'modules' that you can combine to your liking and also develop separately from another. I guess you already kind of do that with the gaming mode. It might even be possible to create 'full releases' by going through the list, selecting everything and pasting it into a new, single preset.

**Comment by yuuiko** [comment]
Yes a lot of things definitely need to be cleaned up as stuff from when this was my personal preset is still lurking around.

As for collab, I think the current, manual way is the best (getting a collaborator's file and merging it in myself, cleaning it up as I go). Ensures that collabs or merge systems can't mess up any wiring or the master.

----

> Maybe think of presets more like 'modules' that you can combine to your liking and also develop separately from another. 

https://github.com/yuuiko/AquaTouch/tree/master/AquaPlugins ;)
Bringing support for it to AQT and building the community / updates logistics needs a little time though.

**Pull request merged**
